### ISSUE TITLE
建议：两个关于用户登录界面的建议

### ISSUE THREAD

**Issue by sooxin** [KOHGYLW/kiftd-source#12]
> 应用版本：1.0.16-RELEASE

首先感谢作者开源如此实用的软件！以下是两点关于登录界面的优化建议：

1. 请不要提供过于详细的登录错误提示信息
  当输入了不存在的账户，页面会提示"账户不存在或未设置"，当输入了正确的账户和密码的错误时，页面会提示密码错误或未设置。这样的信息过于详细，是不安全的。这样会让攻击网站的人更容易遍历出用户名和密码。

2. 建议添加图片验证码
  同样的原因，现阶段登录没有验证码，只需在浏览器控制台执行个简单的脚本，虽然会花点时间，但也是可以暴力破解出用户名和密码的。破解成本很低。
  希望能添加个简单的图片验证码，增加一些破解成本。

Thanks！

**Comment by sooxin** [comment]
才发现这是作者的开发库，该issue我另提到应用发布的库了：https://github.com/KOHGYLW/kiftd/issues/21

**Comment by KOHGYLW** [comment]
您好！图片验证码功能现已加入，该功能在设计时同时考虑到了使用的便捷性和安全性，当一个账户出现一次及以上的密码验证失败后，后续的登入尝试必须经过图片验证码验证。欢迎更新体验。
