### ISSUE TITLE
建议：网页端修改账户密码和创建账户

### ISSUE THREAD

**Issue by hmsjy2017** [KOHGYLW/kiftd-source#13]
建议加入网页端修改账户密码和注册账户功能，这样就不用远程连接服务器来设置了。

**Comment by KOHGYLW** [comment]
您好，该建议已经被很多用户提及了。为了实现kiftd模块化特性，将来可能会考虑单独开发一个插件用来提供相应的web端账户管理功能，用户可以选装。

**Comment by KOHGYLW** [comment]
您好，上述功能在v1.0.25-release中已经加入，欢迎升级体验！同时，预计未来还会为管理员单独提供一个账户在线管理台，方便其在线管理所有账户。
