### ISSUE TITLE
移动端能否添加操作栏？

### ISSUE THREAD

**Issue by jeremy0519** [KOHGYLW/kiftd-source#15]
电脑端有操作栏，但移动端没有，无法进行上传、新建文件夹等操作

**Comment by KOHGYLW** [comment]
您好，移动端是具备操作栏的……您可以点击文件列表上的文件夹名，它会自动展开，之后您可以在展开的菜单中看到操作菜单并进行相应的操作了，其功能与桌面端完全一致。
