### ISSUE TITLE
这样网盘适用面极窄

### ISSUE THREAD

**Issue by sky5454** [KOHGYLW/kiftd-source#18]
## 不解
本软件原理是把文件复制到指定目录下的`fileblocks`并在另一个`db`文件里建立索引，并没有保留原始文件名，而且也不能直接把已有目录下的文件直接进行分享（必须要要通过本软件的内置工具，原理依然是复制文件到`fileblocks`并在另一个`db`文件里建立索引 ）  

有点遗憾，作者为什么要这样做，安全性没有提高但便利性已经大打折扣。

## 建议
直接访问原始目录/文件即可，`db`文件仍然设在软件目录下。然后采用定时扫描目录变动和手动扫描目录变动两种方式搭配来更新索引即可。以 Java 的安全性，仅仅读文件，是可以做到对原始文件零伤害的。

最后，希望软件越来越好....

**Comment by KOHGYLW** [comment]
您好，这一问题也是很多用户询问的焦点。这种设计确实不是为了提高安全性，而是为了【提高管理效率】以及【与操作系统本身的文件名命名规则解耦】：

1. 提高管理效率
尽可能地避免遍历复杂的文件层次。虽然定时扫描并更新DB也能达到同样的目的，但是定时扫描也会增加的硬盘的IO压力（可能对于家庭用户而言影响较大）。

2. 与操作系统本身的文件命名规则解耦
这一点是主要考虑的因素。由于kiftd的用户可能囊括Windows、Mac OS X、Linux三种不同的操作系统，而Windows的文件命名规则与其他两种不一样，这就可能会造成某个特殊的文件名在Linux或Mac OS X下是合法的，而在Windows下就会造成系统异常（例如文件名“aaa?bbb”在Windows下就不合法，而在另外两种操作系统中合法）。为了确保无论何种操作系统的用户都能将文件上传至运行在任意操作系统的kiftd上，避免直接使用原始文件名存储是目前较好的解决方案。

以上。也非常感谢您的建议，这能帮助kiftd不断进步。

**Comment by sky5454** [comment]
1. 对每个目录都建立一个DB文件进行记录，然后以最后更新时间戳来确认文件索引是否过期即可。只要DB文件里记录的更新时间比现有文件早，就表示文件索引需要更新。最后更新时间戳可以直接调用各系统的命令行

2. 使用命名过滤即可，在上下传前提示用户命名可能不合法。以及只复制特殊命名的文件到储存库。

**Comment by KOHGYLW** [comment]
您的建议已经仔细阅读。您提供的设计方案确实可行，能够实现较为高效的文件系统与操作系统的结合。实际上，在kiftd设计之初也考虑过类似的方案，尤其是通过对文件夹的改动进行监听便可实现索引的更新。不过，由于这一方案的逻辑比现有方案更加复杂，因此未能得到采用，而是选择了当前这种流程更加简单的设计。当然，您的建议已经记录，关于是否应将文件系统与操作系统本身的文件存储结合的议题仍需根据情况进行进一步的研究。

**Comment by KOHGYLW** [comment]
关于将文件系统与操作系统本身的文件管理功能直接结合的方案已被放弃，出于未来进行功能升级的考虑（例如实现分布式存储或者对象存储），kiftd仍然决定未来继续采用内置的文件管理方式进行文件存储和读取。
以上，在此还是要再次感谢您的宝贵建议，这是kiftd不断进步的最佳动力！
