### ISSUE TITLE
支持树莓派吗

### ISSUE THREAD

**Issue by hmsjy2017** [KOHGYLW/kiftd-source#19]
树莓派功耗低、价格便宜，用来做一个小型服务器是一个不错的选择。

**Comment by KOHGYLW** [comment]
emmmm……理论上只要能装上java运行环境，内存再超过4个GB，那么就可以运行。

**Comment by KOHGYLW** [comment]
您好，新版本中对于特定Linux系统进行了优化，解决了在特定Linux系统下在线播放功能无法使用的问题，这样一来，kiftd已经能够在嵌入式Linux中运行了（只要硬件配置满足kiftd的最低需求），欢迎体验！

**Comment by zzy-life** [comment]
> 您好，新版本中对于特定Linux系统进行了优化，解决了在特定Linux系统下在线播放功能无法使用的问题，这样一来，kiftd已经能够在嵌入式Linux中运行了（只要硬件配置满足kiftd的最低需求），欢迎体验！

![image](https://user-images.githubusercontent.com/68179477/167629250-98275f0e-d219-4a33-b2ff-4404a0185f60.png)
arm64还不能运行呀

**Comment by zzy-life** [comment]
> 您好，新版本中对于特定Linux系统进行了优化，解决了在特定Linux系统下在线播放功能无法使用的问题，这样一来，kiftd已经能够在嵌入式Linux中运行了（只要硬件配置满足kiftd的最低需求），欢迎体验！

![image](https://user-images.githubusercontent.com/68179477/167629250-98275f0e-d219-4a33-b2ff-4404a0185f60.png)
arm64还不能运行呀

**Comment by zzy-life** [comment]
> > 您好，新版本中对于特定Linux系统进行了优化，解决了在特定Linux系统下在线播放功能无法使用的问题，这样一来，kiftd已经能够在嵌入式Linux中运行了（只要硬件配置满足kiftd的最低需求），欢迎体验！
> 
> ![image](https://user-images.githubusercontent.com/68179477/167629250-98275f0e-d219-4a33-b2ff-4404a0185f60.png) arm64还不能运行呀

我升级了jar包到3.1.1可以支持arm64了
