### ISSUE TITLE
请问可以无缝切换到mysql吗

### ISSUE THREAD

**Issue by 81519434** [KOHGYLW/kiftd-source#21]
如果可以的话，怎么切换呢？

**Comment by KOHGYLW** [comment]
可以使用MySQL数据库作为kiftd的文件系统存储数据库使用。具体方法可以参见程序中附带的《kiftd说明文档》->高级功能->将文件系统数据库替换为MySQL（P73）。

**Comment by KOHGYLW** [comment]
您好，您的问题未收到进一步的补充，默认已解决并将其关闭。如果您有其他疑问，欢迎提交新的issue。
