### ISSUE TITLE
insert语句的写法不是最佳实践

### ISSUE THREAD

**Issue by 81519434** [KOHGYLW/kiftd-source#23]
![image](https://user-images.githubusercontent.com/9690089/67136312-3f532180-f257-11e9-9874-9559ca99ed2e.png)

此处insert语句没有规定字段名，直接插入value。这种写法是不好的。
假设改变了数据库结构，这句话就会报错！
我们一般使用这个格式来insert
```
INSERT INTO table_name ( field1, field2,...fieldN )
                       VALUES
                       ( value1, value2,...valueN );
```

而不是
```
INSERT INTO table_name
                       VALUES
                       ( value1, value2,...valueN );
```

**Comment by KOHGYLW** [comment]
建议已收到。不过实际上这个设计是符合初衷的，因为在最初设计ORM操作类型时就已经明确将insert方法作为基础方法提供，它的作用就是插入一条完整的数据——如果插入不完整则不能通过此方法操作，避免使用时因疏忽导致数据缺失或错位。所以，如果未来改变数据库，那么该SQL也必须修改后才应开始使用，如果还能直接使用它反而违反了该方法的设计初衷。综上，该处暂不决定修改。
