### ISSUE TITLE
无法以图形界面模式启动kiftd

### ISSUE THREAD

**Issue by zaw929** [KOHGYLW/kiftd-source#24]
刚下载的源码，然后下载包，配置maven，运行。使用得编译器是idea
打印出：错误！无法以图形界面模式启动kiftd，您的操作系统可能不支持图形界面。您可以尝试使用命令模式参数“-console”来启动并开始使用kiftd。
错误类型：java.lang.IllegalArgumentException: input == null!（自己打印的）
请问是什么地方的问题，还有怎么以命令模式运行。
尝试运行，报错如下：
C:\Users\12275\Desktop\kiftd-source-master>java -jar kiftd-1.0.25-RELEAS.jar -start
Error: Unable to access jarfile kiftd-1.0.25-RELEAS.jar
谢谢！

**Comment by KOHGYLW** [comment]
如果是IDEA编译的话，一个常见的问题是编译器可能不会自动将源代码路径内的非源代码资源打包至jar内，这会导致程序图标加载失败从而引发您提到的问题——即无法使用图形界面启动。您需要自行修改Maven的打包配置以确保源代码路径下的所有资源（例如png图标）都能被正确打包至jar中。
以命令模式运行的方法是进入编译好jar程序的目录中（注意，编译好的jar程序必须先放置到项目主目录内，即与conf等文件夹同级才能使用，而不是放置在target内），再执行“java -jar kiftd主程序名称 -console”
以上。

**Comment by KOHGYLW** [comment]
您提到的第二个问题可能就是由于您编译好的jar程序仍留在target文件夹内（这是Maven的默认生成路径）而未拷贝至程序主目录内导致的。您需要先将其拷贝出来（即放置到项目主目录中，与conf等文件夹同级）再运行它。

**Comment by KOHGYLW** [comment]
您好，您的问题未接到进一步的反馈，因此默认已经解决。如有其他问题，欢迎您提交新的issue以得到进一步的帮助。
