### ISSUE TITLE
该项目使用springboot的方式，让人很难受

### ISSUE THREAD

**Issue by clever2019** [KOHGYLW/kiftd-source#28]
估计是从springmvc走过来的，有很多东西是重复造的轮子

**Comment by KOHGYLW** [comment]
您好，建议已收到。该项目在开发时确实是从spring MVC项目转换而来的，因此其中也包含了很多遗留的设计习惯，当然，在不影响性能和功能的前提下，它们不会被单独重构（将会继续沿用）以确保后续开发的工作量不至于太大。如果需要，官方也十分鼓励用户单独克隆该项目并对其进行修改完善，从而得到适合自己的版本。以上。
