### ISSUE TITLE
下载源码之后用IDEA打开maven工程，无法正常启动程序，是源码的目录设置有些问题还是必须在Eclipse中打开？

### ISSUE THREAD

**Issue by geduo4612** [KOHGYLW/kiftd-source#3]

**Comment by edgewalk** [comment]
是你自己的问题

**Comment by KOHGYLW** [comment]
您好，这可能是由于项目设置不正确的原因。首先，您必须确保JDK路径及Maven相关配置均正确（替换为自己的环境），之后，需要保证更新Maven项目资源，确保全部资源被正确引入项目。最后，可以在主类直接启动。如仍有问题，欢迎至信询问！
