### ISSUE TITLE
H2数据库 默认密码为静态密码，存在安全隐患

### ISSUE THREAD

**Issue by cnitli** [KOHGYLW/kiftd-source#30]
再不额外指定MYSQL数据库时，作者会启用H2数据库
但H2数据库再默认情况下存在以下隐患：
1. 没有外出配置，用户无法自定义数据账号密码
2. 代码中为静态密码，所有人员检出的代码默认的密码是一致的，容易被攻击

**Comment by KOHGYLW** [comment]
很高兴收到您的反馈，实际上该问题实际上并不会带来额外的安全隐患。
由于kiftd本身就认为自己运行的环境是绝对安全的，因此它对本地数据都不加保护。也就是说，如果破坏者已经获得了运行kiftd计算机的操作权限，那么他根本就不需要去攻破H2数据库，而是可以【直接查看账户配置文件、找到权限足够的账户的密码、然后使用该账户登入系统中盗取数据】，这种情况下，H2数据库的密码加密与否都不会提高系统整体的安全性——因此，在《kiftd说明文档》的“使用须知”一节中，已经明确指出了【必须确保kiftd运行环境的安全】。同时，由于kiftd内置的H2数据库是以本地模式（而非服务器模式）运行的，因此攻击者也无法进行远程登入。
以上，若有进一步的疑问欢迎提出！

**Comment by KOHGYLW** [comment]
您好，由于未收到您的进一步反馈，因此默认该问题已经解决。如果您还有更多疑问，欢迎提交新的issue！
