### ISSUE TITLE
[New Feature] 与AD集成

### ISSUE THREAD

**Issue by IITII** [KOHGYLW/kiftd-source#32]
> 可能想法比较片面   

# 起因

1. 从现阶段看，kiftd 作为一款便捷、开源、功能完善的个人&团队&小型团队网盘服务器系统目前做得确实非常不错了。
2. 但是也正是因为它的便捷、开源、功能完善，我才会萌生让它与 AD 接轨的想法

# 集成的优势

1. 更完善、更灵活的用户和权限管理方式
2. 适用面人群更广，我觉得一些组织，譬如各大高校会更多的考虑该软件来构建一个组织内部的在线网盘
3. 开源，无论组织还是个人都不怎么喜欢把自己的数据轻易交给另外一个人。

# 缺点
* 开发时人力物力的花销  
* 来自一些比较成熟的软件的挑战（比如：seafile）

**Comment by KOHGYLW** [comment]
很高兴收到您的建议！
您的建议已经记录，并将会作为kiftd未来发展的重要参考意见之一！
接入外部账户管理API也正是kiftd未来发展计划的一部分，以便于用户将kiftd与其他系统有机整合。当然，技术可行性、整合后的易用性、性能影响、技术流行趋势与普及度也是重点考虑的部分，具体方案会依据未来的研究结果而定。
最后，再次感谢您的建议，这是kiftd不断完善的最佳动力。
