### ISSUE TITLE
设置setting里文件系统路径管理有bug

### ISSUE THREAD

**Issue by wangtl** [KOHGYLW/kiftd-source#33]
在设置-》文件系统路径管理-》
当选中某一个文件路径，点击修改路径按钮后，点击“否”后，Add按钮和change按钮便不再可点击了。
![image](https://user-images.githubusercontent.com/13795239/81389266-20ad6d00-914c-11ea-97c2-cb30e14654d0.png)

**Comment by KOHGYLW** [comment]
问题已经收到，将立即着手修复并更新！请关注本条issue的回复。

**Comment by KOHGYLW** [comment]
@wangtl 您好，您反馈的问题已经进行了修复，欢迎及时下载最新版本的发行版程序并进行更新。还是要再次感谢您的反馈，这是kiftd不断完善的最佳动力！
