### ISSUE TITLE
提供 Docker 或者 Docker-compose 部署方式，一键部署。

### ISSUE THREAD

**Issue by snowdream** [KOHGYLW/kiftd-source#34]
提供 Docker 或者 Docker-compose 部署方式，一键部署。

**Comment by KOHGYLW** [comment]
您好，由于Java本身已经具备了跨平台优势，因此官方目前暂无推出官方容器版本的计划。官方更推荐您直接在目标平台上安装Java并运行它，这样最为简单和快捷！
