### ISSUE TITLE
增加linux cli客户端上传文件功能

### ISSUE THREAD

**Issue by caihexin** [KOHGYLW/kiftd-source#35]
增加linux cli客户端上传文件功能

**Comment by KOHGYLW** [comment]
您好，该建议已收到。虽然对于无图形化界面的操作系统而言，暂无较好的方式访问kiftd，但单独开发一个客户端同样违背kiftd的初衷，因此目前暂不决定考虑任何客户端的开发计划。关于实现CLI环境下操作的设想，未来还有待进一步研究。
