### ISSUE TITLE
增加.gitignore文件，忽略源码无关的文件（例如：target,.settings,.project）

### ISSUE THREAD

**Issue by songdragon** [KOHGYLW/kiftd-source#5]
1. 忽略IDE相关文件
2. 忽略编译结果文件
3. 忽略日志输出目录

**Comment by KOHGYLW** [comment]
您好，该建议已经收到。编译结果和日志输出目录会在后续版本中忽略。但Eclipse配置文件仍需保留。这源于该仓库是kiftd的在线备份——实际上，开发工作也是直接在该仓库进行的。这样如果某日因意外导致本地项目丢失，还可以从此仓库还原。并且也能够保留该项目的配置以便于在新的Eclipse上继续工作。

**Comment by KOHGYLW** [comment]
经过测试，目前还是决定保留编译目录和系统文件。虽然这可能会导致仓库体积稍大，但对于直接进行调试已经本人开发迁移较为方便，因此还是需要将其提交至服务器，敬请谅解。
