### ISSUE TITLE
请问文件路径是一一对应的吗？

### ISSUE THREAD

**Issue by zzy-life** [KOHGYLW/kiftd-source#61]
比如我在网盘系统里新建了一个文件夹叫text并且上传了一个a.txt   他的目录是/text/a.txt   那么这个文件在服务器里的路径也是/text/a.txt 吗？

**Comment by zzy-life** [comment]
我看了一下  不是一一对应的  而且文件名也被命名了  
这样做的话  我直接用物理方式（不通过网盘）就无法操作这些文件了

**Comment by NanoBooster** [comment]
现在最新版本支持webdav功能了，可以直接挂载到电脑上像正常文件夹一样操作文件

**Comment by zzy-life** [comment]
> 现在最新版本支持webdav功能了，可以直接挂载到电脑上像正常文件夹一样操作文件
