### ISSUE TITLE
pom.xml增加工程自定义路径和jdk版本

### ISSUE THREAD

**Issue by songdragon** [KOHGYLW/kiftd-source#7]
工程中的源码、配置、web页面，均为非标砖的maven目录结构。通过在pom.xml中设置相关路径属性，使IDE可根据pom识别相关路径，避免IDE中单独进行设置。

**Comment by KOHGYLW** [comment]
该问题已收到，针对非Eclipse的项目配置将在后续逐步添加。这需要一定的时间。

**Comment by KOHGYLW** [comment]
您好，最新版源代码中的pom.xml文件已经增加了源代码路径和jdk编译配置。请查看。如有其他需求，欢迎继续提出建议，您的建议将帮助kiftd做的更好！
